name=input("enter your name:")
age=int(input("enter your age:"))
weight=int(input("enter your weight:"))
father=input("enter your father name:")
mother=input("enter your mother name:")
village=input("enter your village:")
mandal=input("enter your mandal:")
district=input("enter your district:")
state=input("enter your state:")
pincode=int(input("enter your pincode:"))
print("name","age","weight","father","mother","village","mandal","district","state","pincode")
